### ISSUE TITLE
Alternate Channel for Private Chats

### ISSUE THREAD

**Issue by KumariAshamaki** [CodingByHarry/scum_discord_bot_os#1]
Ok so not an issue but I was wondering how I would go about sending Squad and Local chats to a separate channel for the sake of player privacy

**Comment by CodingByHarry** [comment]
Hi @KumariAshamaki 

This was originally created for an admin-locked channel. We didn't actually advertise the chat log to players.

It's been a while since I've looked at this codebase but you'd probably need to do some big changes.

Maybe, in the log_parser add another boolean column with public_chat. Set global and local chat to true and squad/admin chat to false. Then in `/lib/ChatFeed.js` you could do `const publicChannel = client.guilds.cache.get(Config.guildId).channels.cache.get(Config.publicChatFeedsChannel);` (and update the config to match) and add another if statement in that block. Something like the below (untested):


```
 Chat.findAll({where: {publishedAt: null}, order: ['sentAt']}).then(chats => {
      chats.forEach(chat => {
        const Colors = {
          Global: "#02f9f9", // Cyan
          Local: "#ffffff", // White
          Squad: "#21f700", // Lime green
        }
        
        const color = Colors[chat.context];
        let content = chat.content;
        if (chat.mentionAdmins) { content += ` ${adminRole.toString()}`; }

        let chatEmbed = new MessageEmbed()
          .setColor(color)
          .setAuthor(`${chat.authorIgn} (${chat.authorSteamId64})`)
          .setDescription(content);

        chat.update({publishedAt: Sequelize.literal('CURRENT_TIMESTAMP')});
        channel.send({embeds: [chatEmbed]});
        
        // NEW ADDITION --
        if (chat.public_chat) {
          publicChannel .send({embeds: [chatEmbed]});
        }
        
      });
    });   
```

End result would be an admin log channel and a public chat channel.

**Comment by KumariAshamaki** [comment]
Yeah, I figured it was for an admin-locked channel just wanted to change that lol. I will give this a try and see what happens. Thank you for the help! :D

**Comment by KumariAshamaki** [comment]
Sorry bit of a noob. So the "Set global and local chat to true and squad/admin chat to false.". Ware do I define this exactly?

**Comment by KumariAshamaki** [comment]
In the sql bit id imagine based on the context column correct? More importantly how lol

**Comment by KumariAshamaki** [comment]
lol I got it "Kinda working" but is only doing admin mentions in the public channel bc I messed up some place when trying to copy how you did the admin mentions. But I mean its not crashing so I call it progress! Sorry if I am bothering im trying to mostly figure it out on my own XD

**Comment by KumariAshamaki** [comment]
SUCCESS! THANK YOU! Legend bro for real I wish to one day have your skill!

**Comment by CodingByHarry** [comment]
Sorry I've been busy these last few days. Glad to hear you were able to get this working anyway.
